version: '3'
services:
  app-database:
    image: postgres:12.1-alpine
    environment:
      POSTGRES_PASSWORD: "abc@12345"
    ports:
      - "15432:5432"
    volumes:
      - /home/vagrant/cadferias-database:/var/lib/postgresql/data 
    networks:
      - app-network
      
  pgadmin:
    image: dpage/pgadmin4:4.15
    environment:
      PGADMIN_DEFAULT_EMAIL: "ceanma@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "abc@12345"
    ports:
      - "180:80"
    depends_on:
      - app-database
    networks:
      - app-network
      
  app-backend:
    build: 
      context: ./backend
      args:
        JAR_FILE: target/cadferias-0.0.1-SNAPSHOT.jar
    image: br.com.cams7/cadferias-backend:0.0.1-SNAPSHOT
    environment:
      JAVA_OPTS: "-agentlib:jdwp=transport=dt_socket,address=5005,server=y,suspend=n"
      SPRING_PROFILES_ACTIVE: "test"
      JDBC_DATABASE_URL: "jdbc:postgresql://app-database:5432/cadferias"
      JDBC_DATABASE_USERNAME: "postgres"
      JDBC_DATABASE_PASSWORD: "abc@12345"
      ORIGIN_URL: "http://172.42.42.200:13000"
    ports:
      - "18080:8080"
      - "15005:5005"
    depends_on:
      - app-database
    networks:
      - app-network 
      
  app-frontend:
    build: 
      context: ./frontend
      args:
        DIST_FILE: dist/cadferias
    image: br.com.cams7/cadferias-frontend:0.0.1-SNAPSHOT
    ports:
      - "13000:3000"
    depends_on:
      - app-backend
    networks:
      - app-network

networks: 
  app-network:
    driver: bridge