version: '3.7'
services:  
  app-database:
    build:
      context: backend/db
      dockerfile: Dockerfile
      args:
        PGHOST: 172.42.42.200
        PGPORT: 15432
        PGUSER: admin
        PGPASSWORD: admin123
        PGDB: cadferias
    image: 172.42.42.200:18083/cadferias-database 
      
  app-backend:
    build:
      context: backend
      dockerfile: Dockerfile
      args:
        ORIGIN_URL: http://172.42.42.200:280
        SPRING_PROFILES_ACTIVE: test
    image: 172.42.42.200:18083/cadferias-backend:0.0.1-SNAPSHOT
    environment:      
      JDBC_DATABASE_URL: "jdbc:postgresql://172.42.42.200:15432/cadferias"
      JDBC_DATABASE_USERNAME: "admin"
      JDBC_DATABASE_PASSWORD: "admin123"
    ports:
      - "28080:8080"
      - "25005:5005"
    restart: always
    depends_on:
      - app-database
    networks:
      - app-network 
      
  app-frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
      args:
        API: http://172.42.42.200:28080/
        PROFILE: test
    image: 172.42.42.200:18083/cadferias-frontend:1.0.0    
    ports:
      - "280:80"
    restart: always
    depends_on:
      - app-backend
    networks:
      - app-network

networks: 
  app-network:
    driver: bridge